import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const ListingView: NextPage = () => {
    const router = useRouter();

    console.log(router.query.id);
    
    const listings = api.listings.get.useQuery(
        {
            listingId: router.query.id as string
        },
        {
            enabled: !!router.query.id
        }
    );

    const listingItem = listings.data;

    if (!listingItem)
        return;

    return (
        <>
            <Head>
                <title>View Listing</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex bg-gray-700 min-h-screen gap-12  flex-col ">
                <div className="container mx-auto flex flex-col gap-12">
                    <h1 className="text-4xl mt-12">
                        {listingItem.name}
                    </h1>
                    <p>
                        {listingItem.description}
                    </p>
                    <p>
                        $ {listingItem.price}
                    </p>
                </div>
            </main>
        </>
    );
}
